// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"composepack/internal/app"
	"composepack/internal/core/chart"
	"composepack/internal/infra/config"
	"composepack/internal/infra/logging"
	"composepack/internal/util/fileloader"
)

// Injectors from wire.go:

// InitializeApplication wires together all dependencies via Google Wire.
func InitializeApplication() (*app.Application, error) {
	config := provideConfig()
	logger := provideLogger()
	fileSystemLoader := fileloader.NewFileSystemLoader()
	fileSystemChartLoader := chart.NewFileSystemChartLoader(fileSystemLoader)
	compositeLoader := chart.NewCompositeLoader(fileSystemChartLoader)
	runtime := app.NewRuntime(config, logger, compositeLoader)
	application := app.NewApplication(runtime)
	return application, nil
}

// wire.go:

// provideConfig supplies the base configuration used across the application.
func provideConfig() config.Config {
	return config.Default()
}

// provideLogger supplies the root logging implementation.
func provideLogger() logging.Logger {
	return logging.NewZerolog(nil)
}
